title: Cayman theme
description: Blog magang berisi kegiatan,dokumentasi,project yang dilakukan selama magang di InterlaceStudies Bali
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
